name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the files
              uses: actions/checkout@v4

            - name: Create .env file
              run: echo "${{secrets.MORATA_ENV}}" > .env
            - name: Build the Docker image
              run: docker build -t tuananh31j/morata_be:v1.0.0 .

            - name: Log in to Docker Hub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Push the Docker image to Docker Hub
              run: docker push tuananh31j/morata_be:v1.0.0

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: Build

        steps:
            - name: Executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script: |
                      sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                      sudo docker pull stripe/stripe-cli
                      sudo docker run --rm -e STRIPE_API_KEY=sk_test_51PCfBhJ2BXtwdiWSUlAIT5Htx5Br8McexHjp61d8g4vjKMWzq8oAi9pqOfI7cFpb5dz85ErILeeG8jDhrseXe4pv00x9I1qZZd stripe/stripe-cli login
                      sudo docker pull tuananh31j/morata_be:v1.0.0
                      sudo docker stop morata-be || true
                      sudo docker rm -f morata-be || true
                      docker run --network="host" --rm -it stripe/stripe-cli -p 5000:5000  listen --forward-to http://host.docker.internal:5000/webhook --skip-verify --api-key sk_test_51PCfBhJ2BXtwdiWSUlAIT5Htx5Br8McexHjp61d8g4vjKMWzq8oAi9pqOfI7cFpb5dz85ErILeeG8jDhrseXe4pv00x9I1qZZd
                      sudo docker run -d --name morata-be -p 80:5000 tuananh31j/morata_be:v1.0.0
